version: '3.9'
services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - '4000:4000'
      - '4001:4001'
    volumes:
      - ./backend:/app
      - /app/node_modules
    stdin_open: true
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - '3000:3000'
    stdin_open: true